//import Navbar from '../components/navbar'

import NavBar from '../components/Navbar.js';
import Head from 'next/head'
import '../styles/globals.css'
import About from '../pages/index.js'
import Research from '../pages/research.js'
import Projects from '../pages/projects.js'
import Experience from '../pages/experience.js'
import Contact from '../pages/contact.js'

export default function App({ Component, pageProps }) {
  return (
    <>
    <Head>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <title>Sathvik Inteti</title>
    </Head>
    <main className='flex w-full h-[100vh] bg-[#FFF8E7] flex-row px-[10%]'>
        <NavBar/>
        <div className='overflow-y-scroll py-[3rem] w-[100%]'>
          <About />
          <Research />
          <Experience />
          <Projects />
          {/* <Contact /> */}
        </div>
    </main>
    </> 
  );
};